In [15]:
import sys
import os

project_root = os.path.dirname(os.path.abspath('..')) 

if project_root not in sys.path:
    sys.path.append(project_root)

from src.layers import Layer, DenseLayer
import numpy as np

In [16]:
layer1 = DenseLayer(
  name="Dense 1",
  output_dim=5,
  activation_name="relu"
)

layer2 = DenseLayer(
  name="Dense 2",
  output_dim=5,
  activation_name="sigmoid"
)

layer3 = DenseLayer(
  name="Dense 3",
  output_dim=5,
  activation_name="linear"
)

x = np.array(
  [
    [1, 2, 8],
    [1, 5, 3],
    [0, 2, 4],
  ]
)

layers = [layer1, layer2, layer3]
input_dim = x.shape[1]

for layer in layers:
  layer.initialize_parameters(input_dim)
  input_dim = layer.output_dim
  

In [17]:
layer2.activation_fnc

<function src.utils.activations.sigmoid(z: numpy.ndarray) -> numpy.ndarray>

In [18]:
A_prev = x

for layer in layers:
  A_prev = layer.forward_pass(A_prev)

In [19]:
layer1.grads

{'dW': array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 'db': array([[0.],
        [0.],
        [0.],
        [0.],
        [0.]])}

In [22]:
y_pred = A_prev
loss = np.mean(y_pred)

dL_dy_pred = y_pred - 0.03
dA = dL_dy_pred


for layer in layers[::-1]:
  dA = layer.backward_pass(dA)


[[ 2.54232562  2.40848184  2.30878974]
 [-0.18877584 -0.20957703 -0.32149564]
 [ 0.92663857  0.99126451  0.82615822]
 [ 0.4325137   0.70287417  0.57472402]
 [-0.41768822 -0.79747492 -0.9376731 ]]


In [23]:
layer1.grads

{'dW': array([[-1.55778897, -1.53380912, -0.69570499],
        [ 1.39124189,  1.20051862,  0.55969854],
        [ 0.10373514,  0.2278443 , -0.02386651],
        [-0.16804373, -0.20968964, -0.10426292],
        [ 1.00023182,  1.10266844,  0.37067615]]),
 'db': array([[-0.47388859, -0.1537548 , -0.09704885],
        [ 0.45689932,  0.09252726,  0.09366101],
        [ 0.18575035,  0.0171411 , -0.01453717],
        [-0.02205409, -0.0312681 , -0.01043168],
        [ 0.46461835,  0.10286942,  0.04123433]]),
 'dA': array([[-0.47388859, -0.1537548 , -0.09704885],
        [ 0.45689932,  0.09252726,  0.09366101],
        [ 0.18575035,  0.0171411 , -0.01453717],
        [-0.02205409, -0.0312681 , -0.01043168],
        [ 0.46461835,  0.10286942,  0.04123433]]),
 'dZ': array([[-0.47388859, -0.1537548 , -0.09704885],
        [ 0.45689932,  0.09252726,  0.09366101],
        [ 0.18575035,  0.0171411 , -0.01453717],
        [-0.02205409, -0.0312681 , -0.01043168],
        [ 0.46461835,  0.10286942,  0.0

In [31]:
layer.params["W"]

array([[ 1.44034271,  0.32672699,  0.79913622],
       [ 1.82968164,  1.52485471, -0.79794405],
       [ 0.77574394, -0.12358264, -0.08427784],
       [ 0.33525227,  0.11761108,  1.18740935],
       [ 0.6213847 ,  0.09934723,  0.36241281]])

In [32]:
layer.grads["dW"]

array([[-1.55778897, -1.53380912, -0.69570499],
       [ 1.39124189,  1.20051862,  0.55969854],
       [ 0.10373514,  0.2278443 , -0.02386651],
       [-0.16804373, -0.20968964, -0.10426292],
       [ 1.00023182,  1.10266844,  0.37067615]])